### PR TITLE
Fix link with libbz2

### PR DESCRIPTION
**Pull request by ryancheung**
@etorth 能问下地图那块是怎么画的吗 你的DBN格式的地图渲染我实在不太能看懂 但是我尝试了 正常读取地图文件 然后画地图 但是道馆的房子不知道怎么画出来 道馆的水池有的

### CODE REVIEW

**Comment by ryancheung** [comment]
另外，你是怎么 把原始客户端的地图格式变成 DBN 压缩数据的呢？

**Comment by etorth** [comment]
thanks man, you are still following this project?
Sorry my later checkin breaks the scene rendering part. must be caused by wrong logic in ABDList.

anyway I removed the DBN encodeing/decoding, I use zstd replaced it.
Because it's too slow at the client launching to traverse the zip entry list, for big DBs.

**Comment by ryancheung** [comment]
@etorth Hi, I just send u a email, could u check it when you available please. :D

**Comment by ryancheung** [comment]
4361544198972_ pic
好奇怪 道馆的房子显示不出来 没画出来 @etorth

**Comment by etorth** [comment]
I will check it, I haven’t take care of the mapeditor for sometime.

**Comment by ryancheung** [comment]
I loaded the map with the original .map file， haven't check if loading the map with ZSDB map data has the problem, I’ll try it when I downloaded all the git lfs file.

**Comment by ryancheung** [comment]
I think I found the reason. It's about wil FileName cases. Wil 文件名大小写问题 haha

**Pull request closed without merging**
