### PR TITLE
Mac os compile fix

### PR DESCRIPTION
**Pull request by ryancheung**

### CODE REVIEW

**Comment by ryancheung** [comment]
macOS上编译成功了，monoserver 也启动了，请问客户端怎么启动呢, 现在 客户端启动提示 "No configuration file found.", 配置文件怎么弄呢？

**Comment by ryancheung** [comment]
找到了，在 client/bin目录

**Comment by ryancheung** [comment]
Texture 资源怎么解压呢

**Comment by etorth** [comment]
我看了一下改动很多，谢谢你的工作！
你花了多久时间从clone到make it compile?

请先到tools/dbcreator中用脚本main.sh创建db
然后用账号test密码123456登录

因为这个project一直是我一个人在弄
很多东西都没来得及做，连个开发文档都没

**Comment by ryancheung** [comment]
花了5个小时左右吧，目前已经跑起来了

**Comment by ryancheung** [comment]
这项目出发点很不错，现在已经实现跨平台client和server，但是感觉还有很多工作要做

**Comment by ryancheung** [comment]
server 部分其实可以不用GUI，直接用conf配置就好，然后跑daemon，简单省事

**Comment by ryancheung** [comment]
我的邮箱 ryancheung.go@gmail.com ，QQ发下我邮箱吧，加个QQ聊~

**Comment by etorth** [comment]
@ryancheung 
Sorry for my late response.
For the GUI thing, before I was thinking of remove it, currently I kept it mainly for the easy use of CommandWindow.

If you try Command/Run Command, you can start an input window and issue LUA function calls to it.
like ```` help("listMap") ```` or ````addMonster(3, 3, 400, 120, true)````, the LUA interpreter is in class MonoServer.

currently I support 16 CommandWindow to run at the same time. More than one because if you put a while loop then the window is occupied by it unless you kill the loop.

I am use FLTK since I am very familiar to it.
If remove it we may need to make some other protocol to talk to MonoServer.
That's should be doable.

BTW, let's keep this thread internationalized.
People may track it and your post is helpful to them.

**Comment by ryancheung** [comment]
For running on windows server, it should have a GUI. We could give it options of using or not using GUI.

For non GUi case, we implement the command line with nonblocking stdin IO.

**Comment by ryancheung** [comment]
BTW, Theron is kind of old. 

If you believe it's OK, I suggest replacing the networking part with: https://github.com/cmangos/mangos-classic/tree/master/src/shared/Network
It was implemented with `boost::asio`.

,and the Threading part with: 
https://github.com/cmangos/mangos-classic/blob/master/src/shared/Threading.h
https://github.com/cmangos/mangos-classic/blob/master/src/shared/Threading.cpp 
https://github.com/cmangos/mangos-classic/blob/master/src/mangosd/CliRunnable.cpp#L588
https://github.com/cmangos/mangos-classic/blob/master/src/mangosd/WorldRunnable.cpp

They are from a wow server project, to which I'm very familiar. And I believe they are the better approach to do these things.

I wonder if we can replace the whole Theron library dependent code with the Threading approach I introduced above.

**Comment by ryancheung** [comment]
Actually, I'm not familiar with  GUI things, like FLTK. But I'm willing to learn more of it.
I'm familiar with server things, I want to contribute this project with you. I want to help with the server side things, and learn the client side things with you.

And I wish one or two years later, we can make a playable cross platform Mir3.

**Comment by etorth** [comment]
@ryancheung 
I'll remove the libxs dependency.

I use theron to make every monster/player/NPC as an actor.
Actually it's the starting point, it helps me to write code without doing lock/unlock too much.
And I want to try out, how much this model can help for a mmorpg server.
It's used for server side internal actor communication only, for server/client, I'm using asio.

For the GUI, maybe latter we can make the monoserver headless
And talk to it by some simple plain text based protocol.

**Your contribution is more than welcome, seriously.**
I start and maintain it about 2+ years, seems a forever project.
Hope we can eventually make it playable.

**Comment by ryancheung** [comment]
OK, I see. But why not to use https://github.com/actor-framework/actor-framework ? Theron was not updated since 2014...

**Comment by etorth** [comment]
@ryancheung 
theron is simple, and seems rock stable.
shouldn't be a big thing if we really need to switch to CAF.

**Comment by Nossiac** [comment]
haha, say Hi to both of you!
I tried it on centos 7, and it failed to compile for a lot of dependency failures.... struggled for a few hours, no luck yet.
I'm pretty interested in the server part. but I think this project is too ambiguous in the arch thus make it too difficult for beginners to start.
I'll try it later when I feel boring..... :-)

**Comment by ryancheung** [comment]
Try to compile with my PR, and install missing libraries cmake noticed

**Comment by ryancheung** [comment]
I'm learning SDL2 and trying to tackle the client part, attempting to figure out how it works.

And I have few questions:
1. I read the `wilimagepackage.hpp` file and figure out the storage structure of *.wil/wix files in client data directory and how to load them. But when come to the client loading textures, it does not load *.wil/wix files, it load Res/Texture/*DBN.ZIP instead. And I check the DBN file related code, found that they are zip files with special data storage format. Then I want to know why not load *.wil/wix directory from client data directory, and what *DBN.ZIP files are and how to create/load the *DBN.ZIP files. These DBN part really confuse me. 😢 

2. Where are the map files, which were found in client Map directory. Are they also stored as DBN? I found a `Res/Map/MapBinDBN.ZIP` file. But the real client map file size is about 450MB. How does the map loading part works?

@etorth

**Comment by etorth** [comment]
@ryancheung 
Sorry for my late response, and thanks for your time to get through all these messes.

for your question:
````wilimagepackage.hpp/cpp```` is used to decode wil/wix,  binaries in ````tools```` use it. As you said, client is using DBN, which basically is just a zip arch, every resource in it get an uint key. and I am using hash map to retrieve it, retrieving the gfx resources takes large amount of time, and I just try to keep it simple. if in client I directly load wil/wix files, I need many lines of code to keep it compatible to many versions for mir2/mir3/woool image libs, lets hide it from client and keep these dirty things in ````tools````.

mir2/3 directly use a 2D memroy and fwrite it to the .map files. It's very big. I also use the 2D memory for runtime, but to read/write to the hard driver, I just compressed it in MapBinDBN.ZIP, it's 10x smaller for file size. 


for your PR:
Sorry I haven't give more comments for your PR.
I would like to not include theron lib directly in the project, if can't find it we can just report error or use the external project of cmake. and I will remove libxs dep as next target. What do you think? Thanks!

Happy new year,
Etorth

**Comment by ryancheung** [comment]
Theron Library's makefile is not as normal as other common libraries, it generates libraries and headers in source directory instead of system directories, like `/usr/local/lib/`, which is kind of confusing for newbies, like me :). I think, for, small external libraries which are not very common(cannot be installed directly using system package managers) or small, e.g. utf8cpp, sol2, astar should be put into the project, and let the project build them. 

See the most popular opensource WoW-WotLK server `https://github.com/TrinityCore/TrinityCore/tree/master/dep`.

**Comment by ryancheung** [comment]
@etorth 能问下地图那块是怎么画的吗 你的DBN格式的地图渲染我实在不太能看懂 但是我尝试了 正常读取地图文件 然后画地图 但是道馆的房子不知道怎么画出来 道馆的水池有的

**Pull request closed without merging**
